<?php

namespace Ais\BimbinganBundle\Repository;

/**
 * BimbinganRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BimbinganRepository extends \Doctrine\ORM\EntityRepository
{
}
